name: Symfony

on:
  push:
    branches: [ master ]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: echo This is the first step of my first job.
      - uses: actions/checkout@v3
      - run: git status
      - run: git pull origin master 
