name: Symfony

on:
  push:
    branches: [ master ]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
     - name: pull command
       uses: appleboy/ssh-action@master
       with:
          host: 51.89.217.40
          username: mailercloud
          key: ssh mailercloud@51.89.217.40
          passphrase: ''
          script: git status
