name: Symfony

on:
  push:
    branches: [ master ]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: echo This is the first step of my first job.
        run: git status
